### ISSUE TITLE
Laundry Room Sensor

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#10]
Parts have been ordered
[Nodemcu](https://www.aliexpress.com/item/1pcs-Wireless-module-NodeMcu-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266-CP2102-with-pcb/32656401198.html?spm=2114.13010608.0.0.94i6xt) and sensor package

[Motion](https://www.aliexpress.com/item/Mini-IR-Pyroelectric-Infrared-PIR-Motion-Human-Sensor-Automatic-Detector-Module-high-reliability-12mm-x-25mm/32749737125.html?spm=2114.13010608.0.0.94i6xt)
[Temperature](https://www.aliexpress.com/item/1pcs-DHT22-Digital-Temperature-and-Humidity-Sensor-AM2302-Module-PCB-with-Cable-For-arduino/32769460765.html?spm=2114.13010608.0.0.94i6xt)
[Humidity](https://www.aliexpress.com/item/1pcs-DHT22-Digital-Temperature-and-Humidity-Sensor-AM2302-Module-PCB-with-Cable-For-arduino/32769460765.html?spm=2114.13010608.0.0.94i6xt)
[Vibration](http://www.ebay.ca/itm/162137277265?_trksid=p2060353.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT)
[Lux](https://www.aliexpress.com/item/Smart-Electronics-TEMT6000-An-ambient-light-sensor-Simulate-the-light-intensity-module-Visible-light-sensor/32583469115.html?spm=2114.13010608.0.0.94i6xt)
[Float](http://www.ebay.ca/itm/302205793860?_trksid=p2060353.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT)

Learn to build and set up for mqtt.
- Use motion to turn on washing machine switch
- Use lux after dark to notify if lights left on by accident
- Use vibration to notify that dryer cycle is complete
- Use humidity and notify if out of range
- Use float in drain tub to notify if clogged. If triggered shut off washing machine.
- Add temperature to whole house reading to help balance HVAC

Look into [Wemo](http://www.bestbuy.ca/en-ca/product/belkin-belkin-wemo-wi-fi-light-switch-f7c030fc-f7c030fc/10271532.aspx?) or [TPLink](http://www.bestbuy.ca/en-ca/product/tp-link-tp-link-wi-fi-smart-light-switch-hs200/10459843.aspx?) switch for the lights. Investigate if neutral wire is already there or if I would have to re-wire that. (Drop ceiling + breaker box in same room)

Add to current laundry room package -https://github.com/Norien/Home-Assistant-Config/blob/master/packages/laundry_room.yaml

**Comment by Norien** [comment]
Look into magnetic open / close sensor for laundry room window. 
https://www.amazon.com/Ademco-945T-WH-Miniature-Surface-Terminals/dp/B000GUQKGC/ref=as_li_ss_tl?_encoding=UTF8&pd_rd_i=B000GUQKGC&pd_rd_r=PJSQNE7X5A69JW0Q4QQV&pd_rd_w=nVb5j&pd_rd_wg=UATd6&psc=1&refRID=PJSQNE7X5A69JW0Q4QQV&linkCode=sl1&tag=vmw0a-20&linkId=31ab4c71e7be7c80c83798819fb3431d

**Comment by Norien** [comment]
Finally my nodeMCU's arrived and I've started playing around with the laundry room sensors.

- The motion sensor is 5v not 3.3v. I was able to get it working by plugging into the VI pin which I have learned is direct voltage from the power source! 
- The vibration sensor is sensitive and never lands on the same pole so I had to create a buffer. This appears to be working great now!
```
homeassistant:
  customize:
    automation.dryer_status:
      friendly_name: 'Dryer Status'
      icon: mdi:brightness-4

automation:
  - alias: 'dryer_status'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_dryer_vibration
        to: 'on'
      - platform: state
        entity_id: binary_sensor.laundry_dryer_vibration
        to: 'off'
    action:
      - service: script.turn_off
        data:
          entity_id: script.dryer_status
      - service: script.turn_on
        data:
          entity_id: script.dryer_status

script:
  dryer_status:
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.dryer_switch
      - delay: '00:00:30'
      - service: homeassistant.turn_off
        entity_id: input_boolean.dryer_switch

input_boolean:
  dryer_switch:
    name: dryer_switch
    icon: mdi:sync
    initial: off
```
The idea is that no matter what pole the sensor is set to, if the automation sees a change it will set an input boolean on for a period of time ( testing at 30 seconds ) then turn it back off. Each time the automation runs it turns off the script and starts over!.


if we see the input_boolean is on for a longer period of time ( testing at 5 mins ) then the dryer must be on.
