### ISSUE TITLE
Remote Power on for wireless desktop PC

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#101]
It's always bothered me my game pc switch was only for off. ** WOL cannot work here as system is connected with wireless AC**

Use [Wemos D1 Mini](http://www.ebay.ca/itm/D1-Mini-NodeMcu-4M-bytes-Lua-WIFI-Development-Boards-ESP8266-by-WeMos/132103238825?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649) with [Relay Shield](http://www.ebay.ca/itm/NEW-Relay-Shield-for-Arduino-WeMos-D1-Mini-ESP8266-Development-Board/401120715108?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649) to simulate button press using [ESPEasy](https://github.com/letscontrolit/ESPEasy/releases/tag/v2.0.0-dev12)

to control relay * 
http://192.168.1.144/control?cmd=GPIO,5,0
http://192.168.1.144/control?cmd=GPIO,5,1

Will need to find a 5v always on inside the case. I think this motherboard has an always on USB port for charging.

*Possible bonus will be to add a temp probe to send case temp to home assistant

![wemos_relay_bb](https://user-images.githubusercontent.com/8930713/31681775-31ab9726-b346-11e7-86df-7ab1fab275ef.png)
![20171017_125220](https://user-images.githubusercontent.com/8930713/31681779-353fe0c2-b346-11e7-80ae-baa105c598c7.jpg)

**Comment by Norien** [comment]
Just finished soldering it all up and connected relay to my motherboard power pins. Works GREAT. None of my usb ports on the motherboard would power the wemos so i just ran the usb cable out to an old phone charger for now ( mainly for testing ) I will have to connect to a 5v power source in the atx cable once i get some more time.

The basic simple home assistant config looks like this.
```
script:
  office_pc_on:
    sequence:
    - service: shell_command.office_relay_1
    - service: shell_command.office_relay_0

shell_command:
  office_relay_0: curl -v http://192.168.1.144/control?cmd=GPIO,5,0
  office_relay_1: curl -v http://192.168.1.144/control?cmd=GPIO,5,1
  office_pc_off: "net rpc shutdown -I 192.168.1.256 -U admin%password"

switch:
  - platform: template
    switches:
      office_pc:
        value_template: "{{ is_state('device_tracker.computer_office', 'home') }}"
        turn_on:
          service: script.office_pc_on
        turn_off:
          service: shell_command.office_pc_off
```
