### ISSUE TITLE
Finn's light automation

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#102]
Add condition for lux, no need for light when sun is bright. We can start somewhere around 43 lux

**Comment by Norien** [comment]
beautiful, will need to play around with what lux level works best for us. 

```
  - alias: 'light_finn'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_room_motion
        to: 'True'
    condition:
      - condition: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        below: 45
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.findlays_room
```
