### ISSUE TITLE
Clean up device_status

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#103]
Add icon templates and friendly names, clean up customize

**Comment by Norien** [comment]
sooo smooth love it!

```
      roomba:
        friendly_name: 'Roomba'
        value_template: "{% if is_state('device_tracker.roomba', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.roomba.state == 'home' %} mdi:roomba {% else %} mdi:alert-outline {% endif %}"
```
