### ISSUE TITLE
It's time to encrypt

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#109]
https://community.home-assistant.io/t/how-issue-a-certificate-from-lets-encrypt-not-using-https-or-http-acme-sh/26072

```
sensor:
  - platform: command_line
    command: !secret check_cert
    name: certificate
    unit_of_measurement: days
    scan_interval: 86400
```
