### ISSUE TITLE
Setup Group in Group for energy readings in office and laundry

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#115]
No need to always display all the energy readings. lets try group in group and see if that makes a little more sense

**Comment by Norien** [comment]
Oh yeah Group in Group is nice! Easy to setup
- The graph is off for sure. I can look into changing that out with something that makes more sense

```
group:
  office:
    name: Office
    control: hidden
    entities:
     - sensor.steam_account
     - switch.office_pc
     - switch.office_lightswitch
     - group.office_energy
  office_energy:
    entities:
     - switch.office_powerbar
     - sensor.office_current
     - sensor.office_draw
     - sensor.office_voltage
     - sensor.office_today
     - sensor.office_yesterday
```

![capture](https://user-images.githubusercontent.com/8930713/32135426-29294cb2-bbcd-11e7-8048-d595843d1a6e.PNG)
![capture](https://user-images.githubusercontent.com/8930713/32135469-bae10320-bbcd-11e7-8fd2-ccdd4ee5940e.PNG)
