### ISSUE TITLE
Set vacation if away for 17 hours

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#121]
Need to build on vacation and presence mimicking

**Comment by Norien** [comment]
testing this, not 100% sure on the logic
```
###### SET VACATION MODE
  - alias: Set vacation mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.away
        to: 'on'
        for:
          hours: 17
      - platform: state
        entity_id: group.justin, group.nicole
        to: 'off'
    action:
      - service_template: >
          {% if states.input_boolean.vacation.state == 'on' %} homeassistant.turn_off
          {% else %} homeassistant.turn_on
          {% endif %}
        entity_id: input_boolean.vacation
```

**Comment by Norien** [comment]
Moved to this idea.
```
  - alias: house_mode_vacation
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.away
        to: 'on'
        for:
          hours: 17
      - platform: state
        entity_id: input_boolean.away
        to: 'off' 
    action:
      - service_template: >
          {% if states.input_boolean.vacation.state == 'off' and states.input_boolean.away.state == 'on' %} homeassistant.turn_on
          {% elif states.input_boolean.vacation.state == 'on' and states.input_boolean.away.state == 'off' %} homeassistant.turn_off
          {% endif %}
        entity_id: input_boolean.vacation
```
