### ISSUE TITLE
UV index API is locked to public

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#20]
Tons of errors today looks like they didn't like us pulling values for personal use. Of course. I guess I'll have to dig for another source.

(value: {"error":"API has been closed for public access. Please contact: aershov24@gmail.com."},

**Comment by Norien** [comment]
https://www.wunderground.com/weather/api

**Comment by Norien** [comment]
Looks like I can pull UV data from wunderground which is a supported component for home assistant. And I can make my own sensor to calculate burn time. Just need to figure out what the index relates to in minutes

**Comment by Norien** [comment]
https://files.gitter.im/home-assistant/home-assistant/1cBz/Capture.PNG

**Comment by Norien** [comment]
This looks to be working ok for me. I did a quick cross reference with my local weather station and was pretty close!
```
###### wunderground
  - platform: wunderground
    api_key: !secret wunderground_key
    pws_id: !secret wunderground_station
    monitored_conditions:
      - UV

#######  UV
# http://beautyinthebackcountry.com/2013/04/09/uv-index-and-spf-explained/
  - platform: template
    sensors:
      uv_burn_time:
### Celtic"all babies and children" = 67Min // caucasian = 100Min // Central Europe = 200Min // south american = 200Min // Middle Eastern = 400Min // African = 500Min
        value_template: "{{ (67 / states.sensor.pws_uv.state | float) | round }} Minutes"
```
