### ISSUE TITLE
Roomba 690 + HA integration?

### ISSUE THREAD

**Issue by shelune** [Norien/Home-Assistant-Config#200]
Hey there can I ask about your integration with Roomba 690? Did it just work using the Roomba itself + HA on your RPi (getting BLID PW etc.) or did you have to get some other hardware too to make it happen?

**Comment by Norien** [comment]
Hi, My Roomba 690 is running SW: 3.2.10 and I was able to retrieve the blid and password with https://github.com/koalazak/dorita980#how-to-get-your-usernameblid-and-password

I am using the official Roomba component.

**Comment by shelune** [comment]
I suppose it's this one https://www.home-assistant.io/components/vacuum.roomba/?

**Comment by Norien** [comment]
This is correct.

```
vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_blid
    password: !secret roomba_pass
```
