### ISSUE TITLE
Don't provide travel time if not home

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#35]
During good morning TTS only provide travel time for who is home

**Comment by Norien** [comment]
If statement added but holly cow this is getting messy. I really need to work on this one. I'd also like to add a random quote at the end and combine workday and weekend TTS.

```
- service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('binary_sensor.workday_sensor', 'off') %} script.good_morning_weekend
          {% elif is_state('binary_sensor.workday_sensor', 'on') %} script.good_morning_workday
          {% endif %}
```

  ```
good_morning_workday:
    sequence:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kitchen
          message: "Good Morning, the weather is {{states('sensor.dark_sky_minutely_summary')}} and {{states('sensor.dark_sky_apparent_temperature') | round}} Degrees. Today's High is {{states('sensor.dark_sky_daily_high_temperature')| round}} with a low of {{states('sensor.dark_sky_daily_low_temperature') | round}}.{% if is_state('sensor.nicole', 'not_home') %}{% elif is_state('sensor.nicole', 'home') %}Travel time this morning is {{states('sensor.nicole_home_to_work')}} minutes, Have a nice day at work{% endif %}"
```

 ```
 good_morning_weekend:
    sequence:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kitchen
          message: "Good Morning, the weather is {{states('sensor.dark_sky_minutely_summary')}} and {{states('sensor.dark_sky_apparent_temperature') | round}} Degrees. Today's High is {{states('sensor.dark_sky_daily_high_temperature')| round}} with a low of {{states('sensor.dark_sky_daily_low_temperature') | round}}. Enjoy your Weekend!"
```
