### ISSUE TITLE
Look in to emailing security camera gifs

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#41]
https://github.com/natm/cctv-gif-buffer

**Comment by Norien** [comment]
wow ok so I've been poking at this one on a few different days and I finally got it working! Well, most of it anyways

- I did a ```wget``` on the repo into my home assistant shell folder
- installed in venv 
```
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```
- Setup ```config.yaml``` file for my camera
```
cameras:
  drive1:
    url: http://192.168.1.xx:8999/shot.jpg
    interval: 2
    auth: basic
    username: USER
    password: PASS
server:
  web:
    port: 8080
    listen: 0.0.0.0
```
- Start the server ( I made this a .sh file so it's easier )
```
cd /home/homeassistant/.homeassistant/shell/gif_maker
source venv/bin/activate
nohup python buffer.py -c config.yaml &
```
or just run the .sh ```bash /home/homeassistant/.homeassistant/shell/gif_maker.sh```

Once server is running I can use a cURL to download the .gif into my home assistant folder
```
curl -o /home/homeassistant/.homeassistant/drive1.gif "localhost:8080/gif?camera=drive1&duration=60&interval=0.25"
```
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.6M  100 18.6M    0     0   868k      0  0:00:21  0:00:21 --:--:-- 5111k
```

On the home assistant side I just made a shell command to launch the curl, set a delay to allow it to process and then attached it to email.

```
script:
  notify_camera:
    sequence:
      - service: shell_command.driveway
      - service: shell_command.driveway2
      - delay: '00:00:30'
      - service: notify.email
        data:
            title: 'Alert'
            message: 'Someone is at our home and we are not!'
            data:
                images:
                    - !secret driveway_camera_photo_path
                    - !secret driveway_camera_gif_path
```
