### ISSUE TITLE
Dog barking too quite. Use max volume

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#46]

**Comment by Norien** [comment]
automation is already set at max.
```
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: '1.00'
```

I couldn't  hear the dogs very well outside the door. I can boost the gain on the actual .mp3
