### ISSUE TITLE
Build, flash and deploy sonoff dual switch

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#48]
Dual bedroom fan control!
* https://github.com/arendst/Sonoff-Tasmota

**Comment by Norien** [comment]
![capture](https://user-images.githubusercontent.com/8930713/27094147-28d6bfa8-5037-11e7-9d1e-dccc862d8e59.PNG)
![20170515_110546_hdr](https://cloud.githubusercontent.com/assets/8930713/26114962/ba1df29a-3a2c-11e7-816f-a78ce3542992.jpg)
![20170515_110559_hdr](https://cloud.githubusercontent.com/assets/8930713/26114967/bcf461de-3a2c-11e7-84e9-91ceeea19552.jpg)
![20170515_110648_hdr](https://cloud.githubusercontent.com/assets/8930713/26114968/be76a1a2-3a2c-11e7-9c6f-67c05ba13469.jpg)

**Comment by Norien** [comment]
Finally Flashed and working great! Thanks @zombu2
```
switch:
###### SONOFF DUAL 1
  - platform: mqtt
    name: "Bedroom Fan A"
    state_topic: "stat/sonoff_dual/POWER1"
    command_topic: "cmnd/sonoff_dual/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
###### SONOFF DUAL 2
  - platform: mqtt
    name: "Bedroom Fan B"
    state_topic: "stat/sonoff_dual/POWER2"
    command_topic: "cmnd/sonoff_dual/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
```
