### ISSUE TITLE
Automatic backup based off last github update

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#50]
With each git hub update automatically backup home assistant config to remote server.

**Comment by Norien** [comment]
Works great. Super fun one to play with.
- mounted an SMB share to my nas ( [How to mount windows shares](https://wiki.ubuntu.com/MountWindowsSharesPermanently) )
- check backup folder time stamp and import to a sensor
- check .git index file for time stamp and import to sensor
- automation to compare 2 the two sensors: if git update > latest backup then run backup script
![backup](https://cloud.githubusercontent.com/assets/8930713/26226927/3e35cdb0-3bfd-11e7-8dba-4e000f85ec03.PNG)
```
sensor:
###### Latest github Commit
  - platform: command_line
    command: "python /home/homeassistant/.homeassistant/shell/latest_commit.py"
    name: 'Latest Github Commit'
    scan_interval: 60

###### Latest config backup
  - platform: command_line
    command: "python /home/homeassistant/.homeassistant/shell/latest_backup.py"
    name: 'Latest Backup'
    scan_interval: 60
```
```
automation:
  - alias: "Auto Backup"
    initial_state: 'on'
    trigger:
      platform: template
      value_template: "{{ states('sensor.latest_github_commit') > states('sensor.latest_backup') }}"
    action:
      - service: script.backup_config
```

latest_backup.py
```
import os.path, time
print("%s" % time.ctime(os.path.getmtime("/mnt/ntserver/home-assistant/")))
```

latest_commit.py
```
import os.path, time
print("%s" % time.ctime(os.path.getmtime("/home/homeassistant/.homeassistant/.git/index")))
```
the actual backup part is in my utilities package:
```
script:
  backup_config:
     sequence:
       - service: tts.clear_cache
       - service: shell_command.backup_config
shell_command:
  backup_config: 'sudo bash /home/homeassistant/.homeassistant/shell/backup_config.sh'
```
backup_config.sh
```
#!/bin/bash
cd /path/to/mounted/SMB/home-assistant && zip -r "Home-Assistant-Backup-$(date +"%Y-%m-%d").zip" /home/homeassistant/.homeassistant/ -x "*.log" -x "/*tts/*" -x "*.db" -x "*.db-shm" -x "*.db-wal" -x "*.mp3"
```
