### ISSUE TITLE
Setup and deploy flic button

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#56]
Great Bluetooth button for the bedside table to launch goodnight and goodmorning scripts.
Thanks to @robotsandcakes_twitter

- https://home-assistant.io/components/binary_sensor.flic
- https://github.com/50ButtonsEach/fliclib-linux-hci
- http://blog.denwilliams.net/2017/05/18/flic-hci-on-raspberry-pi/

**Comment by Norien** [comment]
Flic button is super responsive and so far rock solid. Setup on the bedside table and set to control fan / lights / and a local goodnight.

```

  - alias: 'bedroom flic single'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da71b68e
        click_type: single
    action:
      service: switch.toggle
      entity_id: switch.bedroom_fan

  - alias: 'bedroom flic double'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da71b68e
        click_type: double
    action:
      - service: switch.toggle
        entity_id: switch.bedroom_lamps_
      - service: switch.toggle
        entity_id: switch.led_strip

  - alias: 'bedroom flic hold'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da71b68e
        click_type: hold
    action:
      - service: switch.turn_off
        entity_id: switch.bedroom_tv
      - service: switch.turn_off
        entity_id: switch.bedroom_lamps_
      - service: switch.turn_off
        entity_id: switch.led_strip
      - service: switch.turn_on
        entity_id: switch.bedroom_fan
      - service: switch.turn_on
        entity_id: switch.white_noise
```
