### ISSUE TITLE
Update Home Assistant

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#96]
Update Home assistant to newest version.

**Comment by Norien** [comment]
* https://github.com/home-assistant/home-assistant/pull/9607/files had to update tp_link switch attributes!
* recorder updated:
```
recorder:
  db_url: !secret database
  purge_interval: 10
  purge_keep_days: 10
```
* ```input_slider``` -> ```input_number``` in radio packages
